# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
$schema: https://json-schema.org/draft/2020-12/schema

$ref: '#/definitions/RootOptions'

definitions:

  RootOptions:
    allOf:
      - $ref: '#/definitions/PackageOptions'
    properties:
      packages:
        type: object
        additionalProperties:
          $ref: '#/definitions/PackageOptions'

  PackageOptions:
    type: object
    properties:
      recursive:
        type: boolean
        description: Recurse all subpackages?
      search_embedded:
        type: boolean
        description: |
          Check all types in the package, and manage versions for any
          types which embed the `Versioned` type
